name: Aweful
favicon: null
layout_spectrum: 0.91599
typography_spectrum: 0.79026
title: Developer Journey In Beta
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73349047-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8cbb2d'
    - '#61401b'
    - '#ff7e50'
    - '#03597d'
    - '#eee520'
  brandStrength: 0.8125
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
