name: Aweful
favicon: null
layout_spectrum: 0.91599
typography_spectrum: 0.79026
title: Developer Journey In Beta
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73349047-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2490c'
    - '#f2a922'
    - '#69a62d'
    - '#babf26'
    - '#121212'
  brandStrength: 0.8125
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
