name: Aweful
favicon: null
layout_spectrum: 0.5981918
typography_spectrum: 0.2429271
title: Developer Journey In Beta
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73349047-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4447601
  lightness: 0.9101722
  saturation: 0.1809387
  rhythmicContrast: 0.5102616
purpose: []
